config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  resources :ingredients do
    collection do
      get :search
    end
  end
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "recipes#index"
end

app/models/recipe_ingredient.rb
# == Schema Information
#
# Table name: recipe_ingredients
#
#  id            :integer          not null, primary key
#  amount        :float
#  description   :text
#  recipe_id     :integer          not null
#  ingredient_id :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  before_action :set_recipe_ingredient, only: %i[ show edit update destroy ]

  # GET /recipe_ingredients or /recipe_ingredients.json
  def index
    @recipe_ingredients = RecipeIngredient.all
  end

  # GET /recipe_ingredients/1 or /recipe_ingredients/1.json
  def show
  end

  # GET /recipe_ingredients/new
  def new
    @recipe_ingredient = RecipeIngredient.new
  end

  # GET /recipe_ingredients/1/edit
  def edit
  end

  # POST /recipe_ingredients or /recipe_ingredients.json
  def create
    @recipe_ingredient = RecipeIngredient.new(recipe_ingredient_params)

    respond_to do |format|
      if @recipe_ingredient.save
        format.html { redirect_to recipe_ingredient_url(@recipe_ingredient), notice: "Recipe ingredient was successfully created." }
        format.json { render :show, status: :created, location: @recipe_ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_ingredients/1 or /recipe_ingredients/1.json
  def update
    respond_to do |format|
      if @recipe_ingredient.update(recipe_ingredient_params)
        format.html { redirect_to recipe_ingredient_url(@recipe_ingredient), notice: "Recipe ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe_ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_ingredients/1 or /recipe_ingredients/1.json
  def destroy
    @recipe_ingredient.destroy!

    respond_to do |format|
      format.html { redirect_to recipe_ingredients_url, notice: "Recipe ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_ingredient
      @recipe_ingredient = RecipeIngredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_ingredient_params
      params.require(:recipe_ingredient).permit(:amount, :description, :recipe_id, :ingredient_id)
    end
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/views/recipe_ingredients/_form.html.erb
<%= form_with(model: recipe_ingredient) do |form| %>
  <% if recipe_ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_ingredient.errors.count, "error") %> prohibited this recipe_ingredient from being saved:</h2>

      <ul>
        <% recipe_ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :recipe_id, style: "display: block" %>
    <%= form.text_field :recipe_id %>
  </div>

  <div>
    <%= form.label :ingredient_id, style: "display: block" %>
    <%= form.text_field :ingredient_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_ingredients/_recipe_ingredient.html.erb
<div id="<%= dom_id recipe_ingredient %>">
  <p>
    <strong>Amount:</strong>
    <%= recipe_ingredient.amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe_ingredient.description %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_ingredient.recipe_id %>
  </p>

  <p>
    <strong>Ingredient:</strong>
    <%= recipe_ingredient.ingredient_id %>
  </p>

</div>

app/views/recipe_ingredients/edit.html.erb
<h1>Editing recipe ingredient</h1>

<%= render "form", recipe_ingredient: @recipe_ingredient %>

<br>

<div>
  <%= link_to "Show this recipe ingredient", @recipe_ingredient %> |
  <%= link_to "Back to recipe ingredients", recipe_ingredients_path %>
</div>

app/views/recipe_ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe ingredients</h1>

<div id="recipe_ingredients">
  <% @recipe_ingredients.each do |recipe_ingredient| %>
    <%= render recipe_ingredient %>
    <p>
      <%= link_to "Show this recipe ingredient", recipe_ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe ingredient", new_recipe_ingredient_path %>

app/views/recipe_ingredients/new.html.erb
<h1>New recipe ingredient</h1>

<%= render "form", recipe_ingredient: @recipe_ingredient %>

<br>

<div>
  <%= link_to "Back to recipe ingredients", recipe_ingredients_path %>
</div>

app/views/recipe_ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_ingredient %>

<div>
  <%= link_to "Edit this recipe ingredient", edit_recipe_ingredient_path(@recipe_ingredient) %> |
  <%= link_to "Back to recipe ingredients", recipe_ingredients_path %>

  <%= button_to "Destroy this recipe ingredient", @recipe_ingredient, method: :delete %>
</div>