config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  resources :ingredients do
    collection do
      get :search
    end
  end
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "recipes#index"
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Recipe < ApplicationRecord
    has_many :recipe_ingredients, dependent: :delete_all
    has_many :ingredients, through: :recipe_ingredients
    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
    validates_presence_of :title

    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
  
    before_save :find_or_create_ingredients
  
    def find_or_create_ingredients
      self.recipe_ingredients.each do |recipe_ingredient|
        recipe_ingredient.ingredient = Ingredient.find_or_create_by(name:recipe_ingredient.ingredient.name)
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    #@recipe.recipe_ingredients.build.build_ingredient


  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, recipe_ingredients_attributes: [:amount, :description, :_destroy, :id, ingredient_attributes: [:name, :id]])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe do |recipe_form| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="max-w-sm mx-auto">
<div class="mb-5">
    <%= recipe_form.label :title, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= recipe_form.text_field :title, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white"> <%= t("add_ingredients").capitalize%></h2>
  <div id="recipeIngredients">
    <%= recipe_form.fields_for :recipe_ingredients do |recipe_ingredient_form| %>
      <%= render "recipe_ingredient_fields", f: recipe_ingredient_form %>
    <% end %>
    <div class>
      <%= link_to_add_association "#{t('add').capitalize} ➕", recipe_form, :recipe_ingredients, wrap_object: Proc.new { |recipe_ingredient| recipe_ingredient.build_ingredient; recipe_ingredient }, class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
    </div>
  </div>

  <br />
  <br />
  <%= recipe_form.submit t("save_recipe").capitalize, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
  </form>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="mb-5">
  <%= f.label :name,  class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white"  %>
  <%= f.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="p-5">
        <a href="<%= "/recipes/#{recipe.id}?locale=#{ I18n.locale}" %>">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= recipe.title %></h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"></p>
        <a href="<%= "/recipes/#{recipe.id}?locale=#{ I18n.locale}" %>" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <%=t("read_more").capitalize%>
             <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
        </a>
    </div>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields mb-5">


  <div class="ingredients">
    <%= f.fields_for :ingredient do |ingredient| %>
      <%= render "ingredient_fields", f: ingredient %>
    <% end %>
  </div>
 
  <div class="mb-5">
    <%= f.label :description, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white"  %>
    <%= f.text_field :description, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

   <div class="mb-5">
    <%= f.label :amount, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white"  %>
    <%= f.text_field :amount, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <%= link_to_remove_association  "#{t("remove")} 🗑️".capitalize, f, class:"focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" %>
</div>

app/views/recipes/edit.html.erb
<h1> <%= "#{t("edit").capitalize} #{@recipe.title}" %></h1>

<%= render "form" %>

app/views/recipes/index.html.erb
<div class=" flex flex-row gap-4 items-center">
<h1 class="text-3xl font-bold	mb-4">👨🏻‍🍳 Recipes </h1>
<%= link_to t("new_recipe").capitalize , new_recipe_path , class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
</div>

<div id="recipes" class="grid grid-cols-3 gap-4 mx-auto">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-3xl font-bold mb-4"> <%= "⏲️ #{t("new_recipe").capitalize}" %></h1>
<%= render "form" %>

app/views/recipes/show.html.erb
<div class=" flex flex-row gap-4 items-center">

<h1 class="text-3xl font-bold	mb-4"><%= @recipe.title %></h1>
<div class=" flex flex-row  items-center">
 <%= link_to t("back_to_recipes").capitalize, recipes_path,  class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>

<%= link_to  t("edit_recipe").capitalize, edit_recipe_path(@recipe) ,class:"focus:outline-none text-black bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:focus:ring-yellow-900"%> 
<%= button_to t("destroy_recipe").capitalize, @recipe, method: :delete, class: "focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"%>
</div>
</div>


<h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Ingredients</h2>
<ul class="max-w-md divide-y divide-gray-200 dark:divide-gray-700">
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
     <li class="pb-3 sm:pb-4 pt-1">
        <div class="flex items-center space-x-4 rtl:space-x-reverse">
         <div class="flex-1 min-w-0">
            <p class="text-md font-medium text-gray-900 truncate dark:text-white">
               <%= recipe_ingredient.ingredient.name %>
            </p>
            <p class="text-sm text-gray-500 truncate dark:text-gray-400">
               <%= recipe_ingredient.description %>
            </p>
         </div>
         <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
            <%= recipe_ingredient.amount %>
         </div>
      </div>
    </li>
  <% end %>
</ul>